### Listar Clientes
GET http://localhost:5116/api/cliente/listar

### Buscar Cliente por Nome
GET http://localhost:5116/api/cliente/buscar/João

### Cadastrar Cliente
POST http://localhost:5116/api/cliente/cadastrar
Content-Type: application/json

{
    "Nome": "Maria",
    "Email": "mariabonita@gmail.com",
    "Telefone": "998890987",
    "Endereço": "rua do passarinho 520"
}

### Alterar Cliente
PUT http://localhost:7197/api/cliente/alterar/1
Content-Type: application/json

{
    "Nome": "José"
}

### Deletar Cliente
DELETE http://localhost:7197/api/cliente/deletar/2
