### Listar Clientes
GET http://localhost:5116/api/cliente/listar

### Buscar Cliente por Nome
GET http://localhost:5116/api/cliente/buscar/Maria23221

### Cadastrar Cliente
POST http://localhost:5116/api/cliente/cadastrar
Content-Type: application/json

{
    "Nome": "Maria232212",
    "Email": "mariabonita22@gmail.com",
    "Telefone": "998890987",
    "Endereco": "rua do passarinho 520"
}

### Alterar Cliente
PUT http://localhost:5116/api/cliente/alterar/1
Content-Type: application/json

{
    "Nome": "testealterar2",
    "Email": "mariabonita@gmail.com",
    "Telefone": "998890987",
    "Endereco": "rua do passarinho 520",
    "Locacoes": []
}

### Deletar Cliente
DELETE http://localhost:5116/api/cliente/deletar/1