### Listar Filmes
GET http://localhost:5116/api/filme/listar

### Buscar Filme por Título
GET http://localhost:5116/api/filme/buscar/Forrest%20Gump

### Cadastrar Filme
POST http://localhost:5116/api/filme/cadastrar
Content-Type: application/json

{
    "Titulo": "Os Vingadores2",
    "Ano": 2022,
    "Genero": "Ação",
    "Sinopse": "Uma sinopse do filme",
    "Capa": "URL da capa do filme",
    "Descricao": "Descrição do filme",
    "Disponivel": true,
    "Locacoes": []
}


### Atualizar Filme por ID
PUT http://localhost:5116/api/filme/alterar/2
Content-Type: application/json

{
    "Titulo": "Novo Título do Filme",
    "Ano": 2023,
    "Genero": "Aventura",
    "Sinopse": "Nova sinopse do filme",
    "Capa": "Nova URL da capa do filme",
    "Descricao": "Nova descrição do filme",
    "Disponivel": false,
    "Locacoes": []
}

### Deletar Filme por ID
DELETE http://localhost:5116/api/filme/deletar/1