### Cadastrar uma Locação
POST http://localhost:5116/api/locacao/cadastrar
Content-Type: application/json

{
    "Valor": 10.99,
    "Observacoes": "Observações adicionais (opcional)",
    "FilmeId": null,
    "ClienteId": null
}



### Associar Cliente e Filme a uma Locação Existente
POST http://localhost:5116/api/locacao/associar/{locacaoId}
Content-Type: application/json


{
    "ClienteId": 1,
    "FilmeId": 2
}

### Buscar uma Locação por ID (Read)
GET http://localhost:5116/api/locacao/buscar/2


### Atualizar uma Locação por ID (Update)
PUT http://localhost:5116/api/locacao/atualizar/1
Content-Type: application/json


{
    "Valor": 60.0
    // Adicione outros campos conforme necessário para atualização
}

### Deletar uma Locação por ID (Delete)
DELETE http://localhost:5116/api/locacao/deletar/1


### Listar todas as Locações (Read)
GET http://localhost:5116/api/locacao/listar
